import { test, expect } from "@playwright/test";
import { createDrawing } from "../../src/cad-core.js";
import { nativeBlockDrawing } from "../fixtures/native-block.js";
import { exportDxf } from "../../src/dxf-export.js";
import { parseCadImport } from "../../src/importers.js";
import { readFile } from "node:fs/promises";

test("native BLOCK import, attributes, moves, undo and reload work in the editor", async ({ page }, testInfo) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript((drawing) => { if (!localStorage.getItem("mirai-web-cad-mvp")) localStorage.setItem("mirai-web-cad-mvp", JSON.stringify(drawing)); }, createDrawing());
  await page.route("**/api/**", (route) => route.abort());
  await page.goto("/");
  await expect(page.locator(".save-status")).toHaveText("オフライン");
  const stored = () => page.evaluate(() => JSON.parse(localStorage.getItem("mirai-web-cad-mvp")));
  const command = async (value) => { await page.locator("#commandInput").fill(value); await page.locator("#commandInput").press("Enter"); };
  const fixture = nativeBlockDrawing();
  fixture.unit = "m";
  fixture.entities[0].axisScale = { x: -1, y: 1.5 };
  const source = exportDxf(fixture).content;
  await page.locator("#importFile").setInputFiles({ name: "native.dxf", mimeType: "application/dxf", buffer: Buffer.from(source) });
  await expect.poll(async () => (await stored()).entities.length).toBe(2);
  const original = await stored();
  expect(original.blockDefinitions.length).toBe(2);
  expect(original.unit).toBe("m");
  expect(original.dxfSources[0].source).toBe(source);
  expect(original.entities[0].axisScale).toEqual({ x: -2, y: 3 });
  await command("UNDO");
  expect((await stored()).blockDefinitions).toEqual([]);
  expect((await stored()).unit).toBe("mm");
  await command("REDO");
  expect((await stored()).unit).toBe("m");
  await command(`SELECT ${(await stored()).entities[0].id}`);
  await command("MIRROR 0,0 1,0");
  expect((await stored()).entities[0].axisScale).toEqual({ x: -2, y: -3 });
  await page.locator('#propertyForm [name="layerId"]').selectOption("layer-frame");
  await page.locator("#propertyForm").getByRole("button", { name: "プロパティ更新" }).click();
  expect((await stored()).entities[0].layerId).toBe("layer-frame");
  const id = (await stored()).entities[1].id;
  await command(`SELECT ${id}`);
  const attributeInput = page.locator('[name="blockAttribute_0"]');
  await expect(attributeInput).toHaveValue("測点A");
  await attributeInput.fill("変更済;=1");
  await page.locator("#propertyForm").getByRole("button", { name: "プロパティ更新" }).click();
  expect((await stored()).entities[1].attributeReferences[0].value).toBe("変更済;=1");
  await command(`MOVE ${id} 100,50`);
  expect((await stored()).entities[1].insertion).toEqual({ x: 1100, y: 550 });
  await command("UNDO");
  expect((await stored()).entities[1].insertion).toEqual({ x: 1000, y: 500 });
  await command("REDO");
  await page.reload();
  await expect(page.locator(".save-status")).toHaveText("オフライン");
  expect((await stored()).entities[1].attributeReferences[0].value).toBe("変更済;=1");
  await command(`SELECT ${id}`);
  await expect(page.locator('[name="blockAttribute_1"]')).toHaveValue("測点B");
  await page.getByRole("button", { name: "図面範囲表示", exact: true }).click();
  const pixels = await page.locator("#cadCanvas").evaluate((canvas) => {
    const data = canvas.getContext("2d").getImageData(0, 0, canvas.width, canvas.height).data;
    let count = 0;
    for (let i = 0; i < data.length; i += 4) if (data[i] < 80 && data[i + 1] > 60 && data[i + 1] < 180 && data[i + 2] > 120) count++;
    return count;
  });
  // Canvasのbacking storeはCSS表示寸法と一致する(Issue #78)。旧来の1180x760固定backing storeより画素数が少ないため閾値を下げる。
  expect(pixels).toBeGreaterThan(30);
  await testInfo.attach("native-block-editor", { body: await page.screenshot({ path: testInfo.outputPath("native-block-editor.png"), fullPage: true }), contentType: "image/png" });
  // Export via the actual command dispatcher, including the browser download.
  await page.getByRole("button", { name: "出力", exact: true }).click();
  const downloadPromise = page.waitForEvent("download");
  await page.getByTitle("DXF書出し", { exact: true }).click();
  const download = await downloadPromise;
  const content = await readFile(await download.path(), "utf8");
  const drawing = createDrawing();
  const imported = parseCadImport({ filename: "edited.dxf", content, drawing, currentLayerId: drawing.layers[0].id });
  const references = imported.commands.filter((c) => c.op === "add").map((c) => c.entity);
  expect(references[1].insertion).toEqual({ x: 1100, y: 550 });
  expect(references[1].attributeReferences[0].value).toBe("変更済;=1");
  expect(references[0].axisScale).toEqual({ x: -2, y: -3 });
  expect(errors).toEqual([]);
});
